ipBlacklist = """
b.barracudacentral.org
bl.score.senderscore.com
bl.spamcop.net
cbl.abuseat.org
dnsbl.sorbs.net
dnsbl.spfbl.net
multi.surbl.org
spam.dnsbl.sorbs.net
zen.spamhaus.org
black.dnsbl.brukalai.lt
spam.dnsbl.anonmails.de
bl.mailspike.net""" 

domainBlacklist = """
multi.uribl.com
abuse.spfbl.net
dbl.spamhaus.org
multi.surbl.org"""

cacheControlMaxAge = 3600 # Seconds

redisCacheTTL = 300 # Seconds

maxCustomBlacklists = 20 # Maximum number of custom blacklists allowed in POST requests

maxCustomNameservers = 3 # Maximum number of custom nameservers allowed in POST requests

nameServers = """
100.100.100.100
"""

listenPort = ":8080"