services:
  multicheck:
    build: .
    network_mode: host
    depends_on:
      - valkey
    environment:
      - VALKEY_HOST=127.0.0.1
      - VALKEY_PORT=6379

  valkey:
    image: docker.io/valkey/valkey:9
    network_mode: host
    command: valkey-server /usr/local/etc/valkey/valkey.conf
    volumes:
      - ./valkey.conf:/usr/local/etc/valkey/valkey.conf:ro